// <auto-generated />
using System;
using Foodeez.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foodeez.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Foodeez.Domain.Entities.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("longtext");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("FdcId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FdcSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("ServingSize")
                        .HasColumnType("float");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.ToTable("food_items", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate");

                    b.ToTable("meal_logs", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealLogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MealLogId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealLogId");

                    b.ToTable("meal_log_items", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("FoodItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Servings")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("meal_plan_entries", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<int?>("SpoonacularId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SpoonacularSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FoodItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IngredientName")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Quantity")
                        .HasColumnType("float");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DailyCalorieTarget")
                        .HasColumnType("int");

                    b.Property<float>("DailyCarbTargetG")
                        .HasColumnType("float");

                    b.Property<float>("DailyFatTargetG")
                        .HasColumnType("float");

                    b.Property<float>("DailyProteinTargetG")
                        .HasColumnType("float");

                    b.Property<int>("DietaryGoal")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<float>("HeightCm")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("ProfileCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<float?>("TargetWeightKg")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<float>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.FoodItem", b =>
                {
                    b.OwnsOne("Foodeez.Domain.ValueObjects.NutritionalInfo", "NutritionalInfo", b1 =>
                        {
                            b1.Property<Guid>("FoodItemId")
                                .HasColumnType("char(36)");

                            b1.Property<float>("Calories")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_calories");

                            b1.Property<float>("Carbohydrates")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_carbohydrates");

                            b1.Property<float>("Fat")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_fat");

                            b1.Property<float>("Fiber")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_fiber");

                            b1.Property<float>("Protein")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_protein");

                            b1.Property<float>("Sodium")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_sodium");

                            b1.Property<float>("Sugar")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_sugar");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("food_items");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("NutritionalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealLog", b =>
                {
                    b.HasOne("Foodeez.Domain.Entities.User", "User")
                        .WithMany("MealLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealLogItem", b =>
                {
                    b.HasOne("Foodeez.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Foodeez.Domain.Entities.MealLog", "MealLog")
                        .WithMany("Items")
                        .HasForeignKey("MealLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Foodeez.Domain.ValueObjects.NutritionalInfo", "NutritionalInfo", b1 =>
                        {
                            b1.Property<Guid>("MealLogItemId")
                                .HasColumnType("char(36)");

                            b1.Property<float>("Calories")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_calories");

                            b1.Property<float>("Carbohydrates")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_carbohydrates");

                            b1.Property<float>("Fat")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_fat");

                            b1.Property<float>("Fiber")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_fiber");

                            b1.Property<float>("Protein")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_protein");

                            b1.Property<float>("Sodium")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_sodium");

                            b1.Property<float>("Sugar")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_sugar");

                            b1.HasKey("MealLogItemId");

                            b1.ToTable("meal_log_items");

                            b1.WithOwner()
                                .HasForeignKey("MealLogItemId");
                        });

                    b.Navigation("FoodItem");

                    b.Navigation("MealLog");

                    b.Navigation("NutritionalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("Foodeez.Domain.Entities.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealPlanEntry", b =>
                {
                    b.HasOne("Foodeez.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Foodeez.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Entries")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodeez.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FoodItem");

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.Recipe", b =>
                {
                    b.OwnsOne("Foodeez.Domain.ValueObjects.NutritionalInfo", "NutritionalInfoPerServing", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("char(36)");

                            b1.Property<float>("Calories")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_calories");

                            b1.Property<float>("Carbohydrates")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_carbohydrates");

                            b1.Property<float>("Fat")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_fat");

                            b1.Property<float>("Fiber")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_fiber");

                            b1.Property<float>("Protein")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_protein");

                            b1.Property<float>("Sodium")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_sodium");

                            b1.Property<float>("Sugar")
                                .HasColumnType("float")
                                .HasColumnName("nutrition_sugar");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("NutritionalInfoPerServing")
                        .IsRequired();
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Foodeez.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Foodeez.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("Foodeez.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Foodeez.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealLog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Foodeez.Domain.Entities.User", b =>
                {
                    b.Navigation("MealLogs");

                    b.Navigation("MealPlans");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
