<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>04be86dd-4300-40b8-83a4-4a7fdcbf8080</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Foodeez.Domain\Foodeez.Domain.csproj" />
    <ProjectReference Include="..\Foodeez.Application\Foodeez.Application.csproj" />
    <ProjectReference Include="..\Foodeez.Infrastructure\Foodeez.Infrastructure.csproj" />
  </ItemGroup>
</Project>
